### ISSUE TITLE
Reports the CSS Modules `values` variables are unused

### ISSUE THREAD

**Issue by bz-stripe** [bmatcuk/eslint-plugin-postcss-modules#10]
CSS Modules values variables docs: https://github.com/css-modules/css-modules/blob/master/docs/values-variables.md

Taking the example from the docs

**colors.css**

```css
@value blue: #0c77f8;
@value red: #ff0000;
@value green: #aaf200;
```

**demo.css**

```css
/* import your colors... */
@value colors: "./colors.css";
@value blue, red, green from colors;

.button {
  color: blue;
  display: inline-block;
}
```

I'll see
```
warning   Classes colors, blur, red green mobileBreakpoint are exported but unused   postcss-modules/no-unused-class
```

Possibly related to https://github.com/bmatcuk/eslint-plugin-postcss-modules/issues/7
